import React from "react";

const Courses = () => {
  const sheCodesCourses = [
    {
      title: "SheCodes Basics",
      content: "Fundamentals of HTML, CSS & JavaScript",
      duration: "1 weeks - 20 hr/w",
      link: "https://www.shecodes.io/workshop#curriculum",
    },
    {
      title: "SheCodes Plus",
      content:
        "Advanced of HTML, CSS, Bootstrap & responsive design. Advanced JavaScript, APIs, Git, GitHub & hosting",
      duration: "3 weeks - 20 hr/w",
      link: "https://www.shecodes.io/plus#package",
    },
    {
      title: "SheCodes Responsive",
      content: "Advanced responsive design with Bootstrap",
      duration: "2 weeks - 20 hr/w",
      link: "https://www.shecodes.io/responsive#package",
    },
    {
      title: "SheCodes React",
      content:
        "Fundamentals & advanced React, APIs with real world applications",
      duration: "3 weeks - 20 hr/w",
      link: "https://www.shecodes.io/react#package",
    },
  ];
  const udemyCourses = [
    {
      title: "The complete JavaScript Course 2021: From Zero to Expert!",
      description:
        "The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!",
      content: "319 lectures: 69 hrs of lecture material",
      topics: [
        "Fundamentals in JS",
        "Developer Skills",
        "JS in the Browser: DOM & Events Fundamentals",
        "How JS Works Behind the Scenes",
        "Data Structures, Modern Operators & Strings",
        "Working with Functions",
        "Working with Arrays",
        "Numbers, Dates, Intl & Timers",
        "Advanced DOM & Events",
        "Object-Oriented Programming (OOP)",
        "OOP, Geolocation, External Libraries & More",
        "Asynchronous JS: Promises, Async/Await, AJAX",
        "Modern JS Development: Modules, Tooling & Functional",
        "Building a Modern Application",
        "Settingup Git & Deployment",
      ],
      link: "https://www.udemy.com/course/the-complete-javascript-course/",
    },
    {
      title: "The Complete 2022 Web Development Bootcamp",
      description:
        "Become a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, MongoDB, build real projects",
      content: "441 lectures: 55 hrs of lecture material",
      topics: [
        "Front-End Web Development",
        "Intro to HTML, Intermediate HTML",
        "Intro to CSS, Intermediate CSS",
        "Intro to Bootstrap, Intermediate Bootstrap",
        "Web Design",
        "Intro to JavaScript ES6 & Intermediate ES6",
        "DOM",
        "Advanced JavaScript & DOM Manipulation",
        "JQuery",
        "Unix Command Line",
        "Backend Web Development",
        "Node.js",
        "Express.js with Node.js",
        "APIs - Application Programming Interfaces",
        "Git, Github & Version Control",
        "EJS",
        "Databases",
        "SQL",
        "MongoDB",
        "Mongoose",
        "Putting Everything Together",
        "Deplying Web Applciations",
        "Building RESTful APIs from Scratch",
        "Authentication & Security",
        "React.js",
      ],
      link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    },
    {
      title: "NodeJS - The Complete Guide (MVC, REST APIs, GraphQL, Deno)",
      description:
        "Master Node JS & Deno.js, build REST APIs with Node.js, GraphQL APIs, add Authentication, use MongoDB, SQL & much more!",
      content: "542 lectures: 41 hrs of lecture material",
      topics: [
        "Introduction & JavaScript ES6 Refresher",
        "Understanding the Basics",
        "Improved Development Workflow & Debugging",
        "Working with Express.js",
        "Working with Dynamic Content & Adding Templating Engines",
        "The Model View Controller (MVC)",
        "Enhancing the App",
        "Dynamic Routes & Advanced Models",
        "SQL Intro",
        "Understanding Sequelize",
        "Working with NoSQL & Using MongoDB",
        "Working with Mongoose",
        "Sessions & Cookies",
        "Adding Authentication",
        "Sending Emails",
        "Advanced Authentication",
        "Understanding Validation",
        "Error Handling",
        "File Upload & Download",
        "Adding Pagination",
        "Understanding Async Requests",
        "Adding Payments",
        "Working with REST APIs - The Basics",
        "Working with REST APIs - Practical Application",
        "Understanding Async Await in Node.js",
        "Understanding Websockets & Socket.io",
        "Working with GraphQL",
        "Deplying Apps",
        "Testing Node.js Applications",
        "Node.js as a Build Tool & Using npm",
        "Modern JavaScript & NodeJS",
        "NodeJS & TypeScript",
        "Intro to Deno",
        "Deno, CRUD & Databases (MogoDB)",
        "Roundup",
      ],
      link: "https://www.udemy.com/course/the-complete-web-development-bootcamp/",
    },
  ];
  return <div className="Courses"></div>;
};

export default Courses;
